name: foodfreedomapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher:
  launch_review:
  share:
  fluttertoast:
  firebase_database:
  firebase_auth:
  firebase_core:
  firebase_storage:
  firebase_analytics:
  firebase_messaging: 
  flutter_local_notifications: ^5.0.0+3
  animated_bottom_navigation_bar:
  auto_size_text:
  material_design_icons_flutter: 
  shared_preferences:
  lottie:
  jiffy:
  simple_animations: ^1.3.3
  google_sign_in:
  flutter_facebook_auth: ^3.5.6
  country_icons:
  country_picker:
  email_auth: ^1.0.0
  flutter_svg: ^0.22.0
  toggle_switch: ^0.1.9
  audioplayers: ^0.19.1
  volume: ^1.0.1
  syncfusion_flutter_sliders: ^19.3.55
  dio: ^4.0.4
  path_provider: ^2.0.4
  webview_flutter:
  syncfusion_flutter_charts: ^19.3.56

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  background_image: "assets/splashBackground.png"
  image: assets/logo.png

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "app_logo"
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.otf
    - family: Pattaya
      fonts:
        - asset: fonts/Pattaya-Regular.ttf