Map dataCheckIn = {
  'Amazing': {
    'name': [
      'Peaceful',
      'Happy',
      'Excited',
      'Motivated',
      'Proud',
      'Content',
      'Not Sure',
      'Stressed',
      'Tired',
      'Worried',
      'Anxious',
      'Down',
    ],
    'emoji': [
      'peaceful',
      'happy',
      'excited',
      'motivated',
      'proud',
      'content',
      'notsure',
      'stressed',
      'tired',
      'worried',
      'anxious',
      'down',
    ]
  },
  'Pretty Good': {
    'name': [
      'Peaceful',
      'Happy',
      'Excited',
      'Motivated',
      'Proud',
      'Content',
      'Not Sure',
      'Stressed',
      'Tired',
      'Worried',
      'Anxious',
      'Down',
    ],
    'emoji': [
      'peaceful',
      'happy',
      'excited',
      'motivated',
      'proud',
      'content',
      'notsure',
      'stressed',
      'tired',
      'worried',
      'anxious',
      'down',
    ],
  },
  'Okay': {
    'name': [
      'Peaceful',
      'Happy',
      'Motivated',
      'Content',
      'Not Sure',
      'Stressed',
      'Tired',
      'Worried',
      'Anxious',
      'Irritable',
      'Sad',
      'Unmotivated',
    ],
    'emoji': [
      'peaceful',
      'happy',
      'motivated',
      'content',
      'notsure',
      'stressed',
      'tired',
      'worried',
      'anxious',
      'irritable',
      'sad',
      'unmotivated',
    ],
  },
  'Somewhat Bad': {
    'name': [
      'Anxious',
      'Irritable',
      'Sad',
      'Unmotivated',
      'Angry',
      'Content',
      'Not Sure',
      'Stressed',
      'Tired',
      'Worried',
      'Frustrated',
      'Annoyed',
    ],
    'emoji': [
      'anxious',
      'irritable',
      'sad',
      'unmotivated',
      'angry',
      'content',
      'notsure',
      'stressed',
      'tired',
      'worried',
      'frustrated',
      'annoyed',
    ]
  },
  'Horrible': {
    'name': [
      'Anxious',
      'Irritable',
      'Sad',
      'Unmotivated',
      'Angry',
      'Not Sure',
      'Stressed',
      'Exhausted',
      'Worried',
      'Frustrated',
      'Annoyed',
      'Disappointed',
    ],
    'emoji': [
      'anxious',
      'irritable',
      'sad',
      'unmotivated',
      'angry',
      'notsure',
      'stressed',
      'exhausted',
      'worried',
      'frustrated',
      'annoyed',
      'disappointed',
    ]
  }
};

Map whatMakesYouFeelData = {
  'name': [
    'Myself',
    'Health',
    'Food',
    'Sleep',
    'Relationship',
    'Work',
    'Family',
    'Exercise',
    'Money'
  ],
  'image': [
    'myself',
    'health',
    'food',
    'sleep',
    'relationship',
    'work',
    'family',
    'exercise',
    'money'
  ],
};

var iAlsoFeel = [
  'Down',
  'Tired',
  'Stressed',
  'Content',
  'Relaxed',
  'Irritated',
  'Concerned',
  'Sad',
  'Complacent',
  'Grateful',
  'Restless',
  'Annoyed',
  'Frustrated',
  'Furious',
  'Disappointed',
  'Angry',
  'Discouraged',
  'Panicking',
  'Jittery',
  'Tense',
  'Worried',
  'Satisfied',
  'At Ease',
  'Proud',
  'Lonely',
  'Depressed',
  'Pessimistic',
  'Motivated',
  'Inspired',
  'Enthusiastic',
  'Hyper',
  'Thrilled',
  'Drained',
  'Apathetic',
  'Hopeless',
  'Anxious',
  'Loving',
  'Honored',
  'Fulfilled',
  'Optimistic',
  'Cheerful',
  'Joyful',
  'Exhausted',
  'Grief',
  'Focused',
  'Hopeful',
  'Calm',
  'Unmotivated',
  'Bored',
  'Nervous',
  'Scared',
  'Happy',
];
